name = "cueda-worker"
compatibility_date = "2024-01-01"
pages_build_output_dir = "dist"

[[d1_databases]]
binding = "CUEDA_DEMO" # This MUST match the 'env.DB' variable in your code
database_name = "demo"
database_id = "b2050e90-d2ee-43d6-bd69-b2c8b3d21735"